[options.a]
group = "default group"
description = "A config file."
links = [{ source = "./dotfiles/a", target = "config/a" }]
depends = { system = ["neovim"] }

[options.b]
description = "B config file."
links = [{ source = "./dotfiles/b", target = "config/b" }]

[options.c]
description = ""
links = [{ source = "./dotfiles/c", target = "config/c" }]

[options.d]
description = ""
links = [{ source = "./dotfiles/d", target = "config/d" }]
