[[option]]
name = "a"
group = "default group"
description = "A config file."
links = [{ source = "./dotfiles/a", target = "config/a" }]
depends = { system = ["neovim"] }

[[option]]
name = "b"
description = "B config file."
links = [{ source = "./dotfiles/b", target = "config/b" }]

[[option]]
name = "c"
description = ""
links = [{ source = "./dotfiles/c", target = "config/c" }]

[[option]]
name = "d"
description = ""
links = [{ source = "./dotfiles/d", target = "config/d" }]
